[tool.poetry]
name = "cats"
version = "0.1.2"
description = ""
authors = ["rkavlev <r.kavlev@ritm.media>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
